name: ominiflow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  glassmorphism: ^3.0.0
  intl: ^0.20.2
  fl_chart: ^0.71.0
  flutter_stripe: ^11.5.0
  mercadopago_sdk: ^1.3.0
  animations: ^2.0.11
  font_awesome_flutter: ^10.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
